proyecto_final_v1/teloenvio/teloenvio/urls.py
from django.contrib import admin
from django.urls import path
from tiendaonline import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from tiendaonline.views import home,LoginUsuarioView,CrearProductoView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home,name='home'),
    path('login/', LoginUsuarioView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('productos/', views.lista_productos, name='lista_productos'),
    path('producto/<int:producto_id>/', views.detalle_producto, name='detalle_producto'),
    path('crear_producto/', CrearProductoView.as_view(), name='crear_producto'),
    path('agregar_al_carrito/<int:producto_id>/', views.agregar_al_carrito, name='agregar_al_carrito'),
    path('quitar_del_carrito/<int:producto_id>/', views.quitar_del_carrito, name='quitar_del_carrito'),
    path('carrito/', views.carrito, name='carrito'),
    path('realizar_pedido/', views.realizar_pedido, name='realizar_pedido'),
    path('pedido/<int:pedido_id>/', views.detalle_pedido, name='detalle_pedido'),
    path('agregar_direccion/',views.agregar_direccion, name='agregar_direccion'),
    path('historial_pedidos/', views.historial_pedidos, name='historial_pedidos'),
    path('gestion_productos/', views.gestion_productos, name='gestion_productos'),
    path('eliminar_producto/<int:producto_id>/', views.eliminar_producto, name='eliminar_producto'),
    # path('editar_producto/<int:producto_id>/', views.editar_producto, name='editar_producto'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto_final_v1/teloenvio/tiendaonline/models.py
from django.db import models
from django.contrib.auth.models import User

class Productor(models.Model):
    nombre_contacto = models.CharField(max_length=100)
    RUT = models.CharField(max_length=100)
    razon_social = models.CharField(max_length=100)
    direccion = models.ForeignKey('Direccion', on_delete=models.CASCADE)
    comuna = models.CharField(max_length=100)
    rubro = models.CharField(max_length=100)

class Cliente(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    telefono = models.CharField(max_length=20)
    nombre = models.CharField(max_length=100)
    correo_electronico = models.EmailField()
    identificador = models.CharField(max_length=100)
    numIdentificador = models.CharField(max_length=100)
    direccion = models.ForeignKey('Direccion', on_delete=models.CASCADE)
    comuna = models.CharField(max_length=100)

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    precio = models.PositiveIntegerField()
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to='productos/')
    productor = models.ForeignKey(Productor, on_delete=models.SET_NULL, null=True, blank=True)

class Direccion(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    calle = models.CharField(max_length=100)
    ciudad = models.CharField(max_length=100)
    codigo_postal = models.CharField(max_length=10)

class Carrito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    direccion = models.ForeignKey(Direccion, on_delete=models.SET_NULL, null=True)
    productos = models.ManyToManyField(Producto, through='ItemCarrito')
    total = models.PositiveIntegerField(default=0)

class ItemCarrito(models.Model):
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    precio = models.PositiveIntegerField()

class Pedido(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    direccion = models.ForeignKey(Direccion, on_delete=models.SET_NULL, null=True)
    productos = models.ManyToManyField(Producto, through='ItemPedido')
    fecha = models.DateTimeField(auto_now_add=True)
    total = models.PositiveIntegerField(default=0)
    creado_por = models.ForeignKey(User, related_name='pedidos_creados', on_delete=models.SET_NULL, null=True)
    metodo_pago = models.CharField(max_length=100)
    estado = models.CharField(max_length=20)

class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    precio = models.PositiveIntegerField()

proyecto_final_v1/teloenvio/tiendaonline/forms.py
from django import forms
from .models import Producto, Direccion, Pedido,User,Cliente

class LoginForm(forms.Form):
    username = forms.CharField(label='Usuario', required=True,
                               max_length=50, min_length=5,
                               error_messages={
                                   'required': 'El usuario es obligatorio',
                                   'max_length': 'El usuario no puede superar los 50 caracteres',
                                   'min_length': 'El usuario debe tener al menos 5 caracteres'
                               },
                               widget=forms.TextInput(attrs={
                                   'placeholder': 'Ingrese su usuario',
                                   'class': 'form-control'
                               })
                               )
    password = forms.CharField(label='Contraseña', required=True,
                               max_length=50, min_length=1,
                               error_messages={
                                   'required': 'La contraseña es obligatoria',
                                   'max_length': 'La contraseña no puede superar los 50 caracteres',
                                   'min_length': 'La contraseña debe tener al menos 1 caracter'
                               },
                               widget=forms.PasswordInput(attrs={
                                   'placeholder': 'Ingrese su contraseña',
                                   'class': 'form-control'
                               })
                               )

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre', 'precio', 'descripcion', 'imagen']

class DireccionForm(forms.ModelForm):
    class Meta:
        model = Direccion
        fields = ['calle', 'ciudad', 'codigo_postal']

FORMA_PAGO_CHOICES = [
    ('efectivo', 'Efectivo'),
    ('tarjeta', 'Tarjeta de crédito'),
    ('transferencia', 'Transferencia bancaria'),
]


class PedidoGestionForm(forms.Form):
    cliente = forms.ModelChoiceField(queryset=Cliente.objects.all(), empty_label='Nuevo Cliente', required=False)
    nuevo_cliente_nombre = forms.CharField(max_length=100, required=False)
    nuevo_cliente_direccion = forms.CharField(max_length=100, required=False)
    nuevo_cliente_correo = forms.EmailField(required=False)
    nuevo_cliente_telefono = forms.CharField(max_length=20, required=False)
    productos = forms.ModelMultipleChoiceField(queryset=Producto.objects.all(), widget=forms.CheckboxSelectMultiple)
    cantidades = forms.IntegerField(min_value=1)

class DetallePedidoGestionForm(forms.Form):
    nombre_cliente = forms.CharField(max_length=100, disabled=True)
    direccion_cliente = forms.CharField(max_length=100, disabled=True)
    numero_pedido = forms.CharField(max_length=100, disabled=True)
    productos = forms.CharField(widget=forms.Textarea, disabled=True)
    subtotal = forms.DecimalField(decimal_places=2, disabled=True)
    total = forms.DecimalField(decimal_places=2, disabled=True)

proyecto_final_v1/teloenvio/tiendaonline/views.py
from django.http import HttpResponseBadRequest
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.db.models import Sum, F
from django.contrib.auth.decorators import login_required
from django.views import View
from django.views.generic import TemplateView
from .forms import  LoginForm, DireccionForm, ProductoForm
from .models import Producto, Carrito, Pedido, Direccion, ItemCarrito, Cliente,ItemPedido


def home(request):
    return render(request, 'tiendaonline/index.html')


class LoginUsuarioView(TemplateView):
    template_name = 'registration/login.html'

    def get(self, request, *args, **kwargs):
        form = LoginForm()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('home')
            form.add_error('username', 'Credenciales incorrectas')
            return render(request, self.template_name, {"form": form})
        else:
            return render(request, self.template_name, {"form": form})

#################################### VISTAS AGREGAR CARRITO CLIENTE #############################

def lista_productos(request):
    productos = Producto.objects.all()
    return render(request, 'tiendaonline/lista_productos.html', {'productos': productos})


def detalle_producto(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)
    return render(request, 'tiendaonline/detalle_producto.html', {'producto': producto})


class CrearProductoView(TemplateView):
    template_name = 'tiendaonline/crear_producto.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ProductoForm()
        context['productos'] = Producto.objects.all()
        return context

    def post(self, request, *args, **kwargs):
        form = ProductoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('crear_producto')
        else:
            context = self.get_context_data(form=form)
            return self.render_to_response(context)

def eliminar_producto(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)
    producto.delete()
    return redirect('crear_producto')

@login_required
def agregar_al_carrito(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)
    carrito, _ = Carrito.objects.get_or_create(usuario=request.user)

    # Obtener la cantidad deseada de productos del cuerpo de la solicitud
    cantidad = int(request.POST.get('cantidad', 1))

    if cantidad < 1:
        return HttpResponseBadRequest('La cantidad debe ser mayor o igual a 1')

    # Obtener el precio del producto o establecer un valor predeterminado si no se proporciona
    precio = producto.precio if producto.precio else 0

    # Verificar si el producto ya está en el carrito
    item = carrito.itemcarrito_set.filter(producto=producto).first()

    if item:
        # Si el producto ya existe en el carrito, se actualiza la cantidad
        item.cantidad += cantidad
        item.save()
    else:
        # Si el producto no está en el carrito, se crea un nuevo item
        item = ItemCarrito.objects.create(carrito=carrito, producto=producto, cantidad=cantidad, precio=precio)

    # Actualizar el total del carrito
    carrito.total = carrito.itemcarrito_set.aggregate(total=Sum(F('cantidad') * F('precio')))['total'] or 0
    carrito.save()

    return redirect('carrito')

@login_required
def quitar_del_carrito(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)
    carrito = get_object_or_404(Carrito, usuario=request.user)

    carrito.productos.remove(producto)
    carrito.save()

    return redirect('carrito')


@login_required
def carrito(request):
    carrito = get_object_or_404(Carrito, usuario=request.user)
    items = carrito.itemcarrito_set.all()
    total = 0

    for item in items:
        subtotal = item.precio * item.cantidad
        total += subtotal
        item.subtotal = subtotal

    return render(request, 'tiendaonline/carrito.html', {'carrito': carrito, 'items': items, 'total': total})

def realizar_pedido(request):
    carrito = get_object_or_404(Carrito, usuario=request.user)
    direcciones = Direccion.objects.filter(usuario=request.user)

    if request.method == 'POST':
        direccion_id = request.POST.get('direccion_id')

        if direccion_id:
            direccion = get_object_or_404(Direccion, id=direccion_id, usuario=request.user)
        else:
            form = DireccionForm(request.POST)

            if form.is_valid():
                direccion = form.save(commit=False)
                direccion.usuario = request.user
                direccion.save()
            else:
                return render(request, 'tiendaonline/realizar_pedido.html', {'form': form, 'direcciones': direcciones})

        pedido = Pedido.objects.create(cliente=request.user, direccion=direccion, total=carrito.total, creado_por=request.user)

        for item in carrito.itemcarrito_set.all():
            pedido.productos.add(item.producto, through_defaults={'cantidad': item.cantidad, 'precio': item.precio})

        carrito.productos.clear()
        carrito.save()

        return redirect('detalle_pedido', pedido_id=pedido.id)

    else:
        form = DireccionForm()

    return render(request, 'tiendaonline/realizar_pedido.html', {'form': form, 'direcciones': direcciones})


def agregar_direccion(request):
    if request.method == 'POST':
        form = DireccionForm(request.POST)

        if form.is_valid():
            direccion = form.save(commit=False)
            direccion.usuario = request.user
            direccion.save()

            return redirect('realizar_pedido')
    else:
        form = DireccionForm()

    return render(request, 'tiendaonline/agregar_direccion.html', {'form': form})


def detalle_pedido(request, pedido_id):
    pedido = get_object_or_404(Pedido, id=pedido_id)

    return render(request, 'tiendaonline/detalle_pedido.html', {'pedido': pedido})


    
##################################### GESTION ########################################
def gestion_productos(request):
    productos = Producto.objects.all()
    return render(request, 'tiendaonline/gestion_productos.html', {'productos': productos})

def eliminar_producto(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)
    producto.delete()
    return redirect('gestion_productos')

def agregar_producto(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('gestion_productos')
    else:
        form = ProductoForm()
    return render(request, 'tiendaonline/agregar_producto.html', {'form': form})

################################## HISTORIAL PEDIDO ##################################

from .models import Pedido

def historial_pedidos(request):
    pedidos = Pedido.objects.all()
    return render(request, 'tiendaonline/historial_pedidos.html', {'pedidos': pedidos})

#######################################################################################

proyecto_final_v1/teloenvio/tiendaonline/templates/tiendaonline/agregar_direccion.html
{% extends 'tiendaonline/base.html' %}

{% block content %}
  <h2>Agregar dirección</h2>
  <form method="POST" action="{% url 'agregar_direccion' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar dirección</button>
  </form>
{% endblock %}

proyecto_final_v1/teloenvio/tiendaonline/templates/tiendaonline/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TELOENVIO</title>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/all.min.css">
  
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="#">
      <i class='fas fa-dolly' style='font-size:36px'></i>
      TELOENVIO
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">Inicio</a>
        </li>
  
        {% if user.is_staff %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'historial_pedidos' %}">Gestion pedidos</a>
          </li>
          {% elif user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'historial_pedidos' %}">Tus pedidos</a>
          </li>
          {% endif %}

          {% if user.is_staff %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'gestion_productos' %}">Gestión Productos</a>
        </li>
        {% elif user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'lista_productos' %}">Productos</a>
        </li>
        {% endif %}
        <li class="nav-item">
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" class="nav-link"><i class="ri-logout-box-line"></i>Cerrar Sesión</a>
            {% else %}
                <a href="{% url 'login' %}" class="nav-link"><i class="ri-logout-box-line"></i>Inicia Sesión</a>
            {% endif %}
          </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'carrito' %}">
            <i class="fas fa-shopping-cart cart-icon"></i>
          </a>
        </li>
      </ul>
    </div>
  </nav>
{% block content %}  
{% endblock %}


  <footer>
    <p>&copy; 2023 Nekoffee - Galletas y Café. Todos los derechos reservados.</p>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>

proyecto_final_v1/teloenvio/tiendaonline/templates/tiendaonline/carrito.html
{% extends 'tiendaonline/base.html' %}

{% block content %}
  <h2>Carrito de compras</h2>
  {% if items %}
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>Imagen</th>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Precio unitario</th>
            <th>Subtotal</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for item in items %}
            <tr class="align-middle">
              <td>
                {% if item.producto.imagen %}
                  <img src="{{ item.producto.imagen.url }}" width="100" height="100" alt="{{ item.producto.nombre }}" class="img-thumbnail">
                {% else %}
                  Sin imagen
                {% endif %}
              </td>
              <td>{{ item.producto.nombre }}</td>
              <td>{{ item.cantidad }}</td>
              <td>${{ item.precio }}</td>
              <td>${{ item.subtotal }}</td>
              <td>
                <a href="{% url 'quitar_del_carrito' item.producto.id %}" class="btn btn-sm btn-danger">Eliminar</a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <p>Total: ${{ total }}</p>
    <a href="{% url 'realizar_pedido' %}" class="btn btn-primary">Realizar pedido</a>
    <a href="{% url 'lista_productos' %}" class="btn btn-primary">Seguir Comprando</a>
  {% else %}
    <p>No hay productos en el carrito.</p>
  {% endif %}
{% endblock %}

proyecto_final_v1/teloenvio/tiendaonline/templates/tiendaonline/crear_producto.html
{% extends 'tiendaonline/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <h2 class="mb-4">Crear Producto</h2>
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
            <label for="{{ form.nombre.id_for_label }}">Nombre:</label>
            {{ form.nombre }}
          </div>
          <div class="form-group">
            <label for="{{ form.precio.id_for_label }}">Precio:</label>
            {{ form.precio }}
          </div>
          <div class="form-group">
            <label for="{{ form.descripcion.id_for_label }}">Descripción:</label>
            {{ form.descripcion }}
          </div>
          <div class="form-group">
            <label for="{{ form.imagen.id_for_label }}">Imagen:</label>
            {{ form.imagen }}
          </div>
          <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

proyecto_final_v1/teloenvio/tiendaonline/templates/tiendaonline/detalle_pedido.html
{% extends 'tiendaonline/base.html' %}

{% block content %}
  <h2>Detalle de pedido</h2>

  <p>Número de pedido: {{ pedido.id }}</p>
  <p>Cliente: {{ pedido.cliente }}</p>
  <p>Dirección: {{ pedido.direccion.calle }}, {{ pedido.direccion.ciudad }}, {{ pedido.direccion.codigo_postal }}</p>

  <h3>Productos:</h3>
  <ul>
    {% for item in pedido.itempedido_set.all %}
      <li>{{ item.producto.nombre }} - Cantidad: {{ item.cantidad }} - Subtotal: ${{ item.precio|floatformat:2 }}</li>
    {% endfor %}
  </ul>

  <p>Total: ${{ pedido.total|floatformat:2 }}</p>
{% endblock %}

proyecto_final_v1/teloenvio/tiendaonline/templates/tiendaonline/detalle_producto.html
{% extends 'tiendaonline/base.html' %}

{% block content %}
  <h2>{{ producto.nombre }}</h2>
  <p>Precio: {{ producto.precio }}</p>
  <p>{{ producto.descripcion }}</p>
  <a href="{% url 'agregar_al_carrito' producto.id %}">Agregar al carrito</a>
{% endblock %}

proyecto_final_v1/teloenvio/tiendaonline/templates/tiendaonline/gestion_productos.html
{% extends 'tiendaonline/base.html' %}

{% block content %}

<table class="table">
  <thead>
    <tr>
      <th>Imagen</th>
      <th>Nombre</th>
      <th>Precio</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    {% for producto in productos %}
    <tr>
      <td>
        {% if producto.imagen %}
          <img src="{{ producto.imagen.url }}" class="img-thumbnail" alt="{{ producto.nombre }}" style="max-width: 100px;">
        {% else %}
          <span>No disponible</span>
        {% endif %}
      </td>
      <td>{{ producto.nombre }}</td>
      <td>{{ producto.precio }}</td>
      <td>
        <a href="{% url 'eliminar_producto' producto.id %}" class="btn btn-danger">Eliminar</a>
        {% comment %} <a href="{% url 'editar_producto' producto.id %}" class="btn btn-primary">Editar</a> {% endcomment %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

  <a href="{% url 'crear_producto' %}" class="btn btn-success float-right">Agregar nuevo producto</a>
{% endblock %}

proyecto_final_v1/teloenvio/tiendaonline/templates/tiendaonline/historial_pedidos.html
{% extends 'tiendaonline/base.html' %}

{% block content %}
  <h1>Historial de Pedidos</h1>
  {% if pedidos %}
    <table class="table">
      <thead>
        <tr>
          <th>ID del Pedido</th>
          <th>Cliente</th>
          <th>Fecha de Pedido</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for pedido in pedidos %}
          <tr>
            <td>{{ pedido.id }}</td>
            <td>{{ pedido.cliente }}</td>
            <td>{{ pedido.fecha }}</td>
            <td>
              {% comment %} <a href="{% url 'editar_pedido' pedido.id %}" class="btn btn-primary">Editar</a> {% endcomment %}
              <a href="#" class="btn btn-primary">Editar</a>
            </td>
            <td>
              {% comment %} <form action="{% url 'eliminar_pedido' pedido.id %}" method="post"> {% endcomment %}
                <form action="#" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Eliminar</button>
              </form>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No hay pedidos registrados.</p>
  {% endif %}
{% endblock %}

proyecto_final_v1/teloenvio/tiendaonline/templates/tiendaonline/index.html
{% extends 'tiendaonline/base.html'%}

{%block content%}

<div class="jumbotron text-center">
    <h1 class="display-4">¡Bienvenido a Te Lo Envío!</h1>
    <p class="lead">Enviamos tus productos favoritos</p>
    <hr class="my-4">
    <p>Nuestros clienente nos prefieren</p>
    <a class="btn btn-primary btn-lg" href="#" role="button">Ver más</a>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="card">
          <img src="cookie.jpg" class="card-img-top" alt="Galletas">
          <div class="card-body">
            <h5 class="card-title">Soluciones Persona</h5>
            <p class="card-text"></p>
            <a href="#" class="btn btn-light">Ver más</a>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card">
          <img src="coffee.jpg" class="card-img-top" alt="Café">
          <div class="card-body">
            <h5 class="card-title">Soluciones Empresa</h5>
            <p class="card-text"></p>
            <a href="#" class="btn btn-light">Ver más</a>
          </div>
        </div>
      </div>
    </div>
  </div>


{% endblock%}

proyecto_final_v1/teloenvio/tiendaonline/templates/tiendaonline/lista_productos.html
{% extends 'tiendaonline/base.html' %}

{% load static %}

{% block content %}
  <h1 class="text-center mb-4">Productos disponibles</h1>
  <div class="container">
    <div class="row">
      {% for producto in productos %}
        <div class="col-md-3">
          <div class="card mb-4">
            {% if producto.imagen %}
              <img src="{{ producto.imagen.url }}" class="card-img-top shadow object-fit cicular-image " alt="{{ producto.nombre }}">
            {% else %}
              <img src="{% static 'tiendaonline/images/placeholder.png' %}" class="card-img-top rounded-circle shadow object-fit" alt="Imagen de Producto">
            {% endif %}
            <div class="card-body">
              <h5 class="card-title text-primary">{{ producto.nombre }}</h5>
              <p class="card-text">Precio: ${{ producto.precio }}</p>
              <p class="card-text">{{ producto.descripcion }}</p>

              <form action="{% url 'agregar_al_carrito' producto.id %}" method="POST">
                {% csrf_token %}
                <div class="input-group mb-3">
                  <input type="number" class="form-control" name="cantidad" min="1" value="1">
                  <div class="input-group-append">
                    <button class="btn btn-danger btn-block rounded-pill" type="submit">Agregar al carrito</button>
                  </div>
                </div>
              </form>

              <a href="{% url 'detalle_producto' producto.id %}" class="btn btn-light btn-block rounded-pill">Ver detalles</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}